services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: my_laravel_app
    ports:
      - "8000:80"    # Nginx Web Traffic
      # - "5173:5173"  # Vite / NPM Hot Reloading
    volumes:
      - ./:/var/www/html
    environment:
      - PUID=${UID:-1000}
      - PGID=${GID:-1000}
      - APP_ENV=production
    restart: unless-stopped